controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
generuj_raport:
    path: '/generuj-raport/{number}/{start}'
    controller: 'App\Controller\RaportController::generujRaport'
room_controller:
    path: /{building}/{number}
    controller: App\Controller\QRController::redirectToRoom
    requirements:
        number: \d+
